### PR TITLE
Chef-Solo support

### PR DESCRIPTION
**Pull request by xrl**
I had to patch application_nginx to work with Chef Solo. Added some documentation to explain what I was going for and how to use the changes.

### CODE REVIEW

**Comment by sethvargo** [comment]
Hey @xrl! Thank you for supporting the Opscode Cookbooks! Our process has a couple prerequisites before we can merge your contribution. We need to ensure you've completed a Contributor License Agreement (CLA) and a ticket on our ticket tracker for the release workflow. Pull requests are optional, but should always include the ticket number that they're related to for cross-referencing. Please take a moment to review the below wiki page for the appropriate steps:
- http://wiki.opscode.com/display/chef/How+to+Contribute
- http://wiki.opscode.com/display/chef/Code+Review

Also, it looks like this will not merge cleanly. Could yo please rebase off master?

**Comment by cjerdonek** [comment]
This looks like a duplicate of pull request #11 (though that request was filed after this one).  That request also has a link to a ticket.  I think I prefer the other pull request since it doesn't have any references to `Chef::Config[:solo]`.

**Comment by cjerdonek** [comment]
Actually, pull request #8 (which was replaced by #11) precedes this one.

**Comment by benlangfeld** [comment]
This is a dup of #11 and can be closed.

**Comment by benlangfeld** [comment]
Does this cookbook need maintainer-ship assistance? I'd be happy to pitch in to get these things moving at a more regular pace.

**Comment by sethvargo** [comment]
@coderanger would be the one to answer that @benlangfeld

**Comment by benlangfeld** [comment]
Yup. Unfortunately he seems to be too busy to respond here :(

**Comment by coderanger** [comment]
This was already done in #11, as noted above.

**Comment by benlangfeld** [comment]
Thanks @coderanger. Just need #11 in a release now as per #16. Momentum :+1:

**Pull request closed without merging**
