### PR TITLE
Forward from Nginx request details

### PR DESCRIPTION
**Pull request by dmitriy-kiriyenko**
For now, this kind of proxy_pass does not pass request host and request ip, that can break application logic totally.

For example, in rails application methods like `root_url` just don't work - they have nginx upstream name as a host.

### CODE REVIEW

**Comment by dmitriy-kiriyenko** [comment]
Do you still support your cookbook?

1882708e-451a-11e2-8216-27f9c5f86fe9

**Comment by benlangfeld** [comment]
+1

**Comment by josephholsten** [comment]
Do you have a ticket for this in at http://tickets.opscode.com? Have you signed the CLA?

**Comment by josephholsten** [comment]
I've created a ticket for you: http://tickets.opscode.com/browse/COOK-2730

**Comment by jtimberman** [comment]
Hi @dmitriy-kiriyenko!

Thank you for this pull request. As Joseph pointed out, we do require a jira ticket, and a CLA signed for all contributions; the process is described in the CONTRIBUTING file of this repository if you'd like to refer to it. We review COOK tickets three times weekly; for more about our maintenance process for cookbooks, see [the wiki page on the subject|http://wiki.opscode.com/display/chef/Opscode+Cookbook+Maintenance+Processes]. 

That said, PR #3 has a little more control over the configuration through the resource, and we'll review it in full during one of the [code review meetings|http://wiki.opscode.com/display/chef/Code+Review] soon.

Cheers,
Joshua

**Pull request closed without merging**
