### PR TITLE
Add docs for new hosts parameter provided by #11

### PR DESCRIPTION
**Pull request by benlangfeld**
This completes the requirements for #11. Is there any chance this could result in a swift merge and release of that feature? Not having it available is causing me some pain right now :(

### CODE REVIEW

**Comment by lpradovera** [comment]
+1 for the merge, it is very useful.

**Comment by benlangfeld** [comment]
It would be really helpful if this could be merged/released. Anything in particular holding it up?

**Comment by benlangfeld** [comment]
@poise / @coderanger What can I do to help?

**Comment by coderanger** [comment]
Thanks for the patch!

**Pull request merged**
