### PR TITLE
[COOK-3254] Allow app_nginx to work under solo

### PR DESCRIPTION
**Pull request by dstufft**
https://tickets.opscode.com/browse/COOK-3254

A continuation of #8 that moves the logic into the provider.

### CODE REVIEW

**Comment by sethvargo** [comment]
Hey @dstufft! Thank you for supporting the Opscode Cookbooks! Our process has a couple prerequisites before we can merge your contribution. We need to ensure you've completed a Contributor License Agreement (CLA) and a ticket on our ticket tracker for the release workflow. Pull requests are optional, but should always include the ticket number that they're related to for cross-referencing. Please take a moment to review the below wiki page for the appropriate steps:
- http://wiki.opscode.com/display/chef/How+to+Contribute
- http://wiki.opscode.com/display/chef/Code+Review

Also, it looks like this will not merge cleanly. Could yo please rebase off master?

**Comment by dstufft** [comment]
Pretty sure i've signed a CLA, this was months ago so I could be remembering wrong.

I can rebase it this week sometime.

**Comment by cjerdonek** [comment]
The new `hosts` attribute should probably be documented in the README.

**Comment by dstufft** [comment]
Not gonna lie I'm not sure if i'll get time to do this or not :( Some stuff came up, if someone else wants to take it over that's fine with me.

**Comment by benlangfeld** [comment]
What needs doing to get this merged/released, @sethvargo?

**Comment by sethvargo** [comment]
@someara ^

**Comment by benlangfeld** [comment]
Docs pull request coming right up.

**Comment by benlangfeld** [comment]
Anything more I can do to get this merged quicker?

**Comment by lpradovera** [comment]
+1 for being able to run tests on Vagrant. This is a huge blocker.

**Comment by sashich** [comment]
+1

**Comment by benlangfeld** [comment]
@coderanger #13 is redundant without this being merged.

**Comment by coderanger** [comment]
Oh hah, I thought this was merged long ago.

**Comment by benlangfeld** [comment]
Any chance this could be included in a swift release to the community site, @coderanger?

**Comment by benlangfeld** [comment]
@coderanger Do you need a co-maintainer to assist with the review/merge/release process? Frankly I'm dying for this to be included in a release.

**Pull request merged**
